### ISSUE TITLE
pendingFriends method missing data attribute

### ISSUE THREAD

**Issue by stephenyeargin** [arei/node-untappd#20]
When working with the `pendingFriends` method, I noticed that the `data` argument is dropped. ~This is expected, as there is nothing additional that can be passed to this endpoint~ Edit: Turns out, you can pass a `limit` and `offset`. However, the method itself still expects it and will throw a `ReferenceError`.

https://github.com/arei/node-untappd/blob/02ef1ea9f83d8b13e7c7b5e675bbc8ab10999e78/UntappdClient.js#L360-L366

I get an error when running the code in `v0.5.0`:

```
[Thu Mar 25 2021 19:32:50 GMT-0500 (Central Daylight Time)] ERROR ReferenceError: data is not defined
    at UntappdClient.that.pendingFriends (/Users/yeargism/Sites/hubot-untappd-friends/node_modules/node-untappd/UntappdClient.js:362:3)
    at approveRequests (/Users/yeargism/Sites/hubot-untappd-friends/src/untappd-friends.coffee:286:13)
    at TextListener.callback (/Users/yeargism/Sites/hubot-untappd-friends/src/untappd-friends.coffee:66:27)
    at executeListener (/Users/yeargism/Sites/hubot-untappd-friends/node_modules/hubot/src/listener.js:79:16)
    at allDone (/Users/yeargism/Sites/hubot-untappd-friends/node_modules/hubot/src/middleware.js:56:7)
    at /Users/yeargism/Sites/hubot-untappd-friends/node_modules/async/lib/async.js:274:13
    at Object.async.eachSeries (/Users/yeargism/Sites/hubot-untappd-friends/node_modules/async/lib/async.js:142:20)
    at async.reduce (/Users/yeargism/Sites/hubot-untappd-friends/node_modules/async/lib/async.js:268:15)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

**Comment by arei** [comment]
Thank you for you PR!
